{% set name = "pyjuliapkg" %}
{% set pypi_name = "juliapkg" %}
{% set version = "0.1.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/juliapkg-{{ version }}.tar.gz
  sha256: 8bd0af7ce08083e22fb9b082b909bf3f42253086cc37912e938748adf86685b9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - semantic_version >=2.9,<3.dev0

test:
  imports:
    - juliapkg
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JuliaPy/pyjuliapkg
  summary: Julia version manager and package manager
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MilesCranmer
    - mkitti
