{% set name = "pyjuliapkg" %}
{% set pypi_name = "juliapkg" %}
{% set version = "0.1.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/juliapkg-{{ version }}.tar.gz
  sha256: a36096fed2ddfe6fbd1af9bfd1b182136d84a660d0c4187539194229fb383720

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - semver >=3.0,<4.dev0
    - filelock >=3.16,<4.dev0

test:
  imports:
    - juliapkg
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/JuliaPy/pyjuliapkg
  summary: Julia version manager and package manager
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MilesCranmer
    - mkitti
